# Generated by Django 5.0 on 2026-04-06 08:45

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=1023)),
                ('file', models.FileField(blank=True, upload_to='rag_dataset')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date added')),
                ('uploader', models.ForeignKey(blank=True, on_delete=models.SET(None), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
