# Generated by Django 5.0.14 on 2026-04-09 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='databasefile',
            name='gcs_uri',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='databasefile',
            name='rag_resource_name',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='databasefile',
            name='source_type',
            field=models.CharField(choices=[('file', 'File Upload'), ('text', 'Text Upload')], default='file', max_length=10),
        ),
    ]
